Database tooling
lewagon/setup pull request #365
Opened 2022-03-11 09:07 UTC by santiagosan93

This PR focuses in implementing the [DataBase tooling update](https://www.notion.so/lewagon/Database-tooling-3974fc1465ac4014aa76197eabf87d95)

## Changes
- [x] Adds sqlite package installation instructions

2022-03-31 11:00 UTC, dmilon requested changes
Nice work @santiagosan93 :raised_hands: Few comments below :pray:

2022-03-31 11:00 UTC, dmilon commented on _partials/windows_sqlite.md
> +## SQLite
When our the content is identical between Windows and Ubuntu partials, no need to create two. Our convention is to create a unique partial named `sqlite.md` which is going to hold the shared content between multiple OS.

2022-03-31 11:00 UTC, dmilon commented on _partials/ubuntu_sqlite.md
> +[SQLite](https://sqlite.org/index.html) is a database engine used to execute CRUD commands on databse files. Let's install it with `homebrew` .
If we put SQLite before PostgreSQL, then we can move the database intro sentence here and adapt it a bit: 

```suggestion
In a few weeks, we'll talk about databases and SQL. [SQLite](https://sqlite.org/index.html) is a database engine used to execute CRUD commands on database files. Let's install it:
```

Then we could update the PostgreSQL section intro sentence with something like: 
> Sometimes, SQLite is not enough and you will need a more advanced too called PostgreSQL, an open-source, robust and production-ready database system.

2022-03-31 11:00 UTC, dmilon commented on _partials/ubuntu_sqlite.md
> +You should see a version. If not, ask a teacher.
Let's add our conventional emojis here: 

```suggestion
:heavy_check_mark:  If you see a version, you're good +1
:x:  If not, ask for a teacher
```

2022-03-31 11:00 UTC, dmilon commented on _partials/windows_sqlite.md
> +[SQLite](https://sqlite.org/index.html) is a database engine used to execute CRUD commands on databse files. Let's install it with `homebrew`.
Let's copy-paste the new intro sentence here.

2022-03-31 11:00 UTC, dmilon commented on _partials/windows_sqlite.md
> +
Extra empty line: 

```suggestion
```

2022-03-31 11:00 UTC, dmilon commented on _partials/windows_sqlite.md
> +You should see a version. If not, ask a teacher.
Let's copy-paste end-of-section emojied sentences here :pray:

2022-04-05 10:42 UTC, santiagosan93 commented
Thanks for the review @dmilon. Feedback has been implemented 👍

2022-04-06 10:16 UTC, dmilon reviewed
Thank you for the update @santiagosan93 :pray: Just a question about the dependency of VS Code SQLite extension on SQLITE :point_down:

2022-04-06 10:16 UTC, dmilon commented on build.rb
> +  vscode_extensions
I'ld rather keep the `vscode_extensions` partial just after the VS Code installation instructions partial, where it was. Do we need to have SQLite already installed when we install the VS Code SQLit extension? :thinking:

2022-04-06 10:16 UTC, dmilon commented on build.rb
> +  sqlite
Same.

2022-04-06 10:16 UTC, dmilon commented on build.rb
> +  sqlite
Same.

2022-04-06 10:27 UTC, dmilon commented on build.rb
> +  vscode_extensions
I've uninstalled sqlite and the extension on my Linux machine and I can install back the extension without having sqlite binay installed yet. It's not working of course but the extension installation process is still working. Let's restore the `vscode_extensions` position then :pray:

2022-04-06 12:07 UTC, merged