Set terminal default size in macOS
lewagon/setup pull request #389
Opened 2022-06-13 09:12 UTC by brunolajoie

about 3 times bigger than default one

Before
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/22095643/173320548-46cbe8eb-0a22-4ec8-830c-2fdf88727577.png">

After

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/22095643/173320377-6aa8d2d4-948f-4410-89a6-62b66e0d4bf1.png">

2022-06-13 09:18 UTC, dmilon requested changes
Nice improvement :+1: :pray: Could you just add a screenshot with highlighted call to actions, just like we do [here](https://github.com/lewagon/setup/raw/master/images/macos_terminal_pro.png) for example :pray:

2022-06-13 13:02 UTC, dmilon approved these changes
:+1: :pray:

2022-06-13 13:03 UTC, merged

2022-06-22 02:51 UTC, lucasgday commented
Hey @dmilon should we translate these changes to Spanish?

2022-06-23 09:11 UTC, dmilon commented
Hi @lucasgday :wave: Yes you can :+1: Open a PR and put me as reviewer :ok_hand:

2022-08-05 16:46 UTC, lucasgday commented
Here it is @dmilon [PR402](https://github.com/lewagon/setup/pull/402). Could you review, merge and then regenerate the Spanish setup guide?
Thanks!